name: Insert build main

on:
  push:
    branches:    
      - main
    paths:
      - 'Frends.MongoDB.Insert/**'
  workflow_dispatch:

jobs:
  build:
    uses: FrendsPlatform/FrendsTasks/.github/workflows/linux_build_main.yml@main
    with:
      workdir: Frends.MongoDB.Insert
      prebuild_command: docker-compose -f ./Frends.MongoDB.Insert.Tests/Files/docker-compose.yml up -d
    secrets:
      badge_service_api_key: ${{ secrets.BADGE_SERVICE_API_KEY }}